@BaseURL = http://localhost:9090

####

GET {{BaseURL}}/v1/buckets

#####

@BucketName = people

POST {{BaseURL}}/v1/buckets
Content-Type: application/json

{
  "name": "{{BucketName}}",
  "schema": [
    {
      "field": "id",
      "type": "string",
      "not-null": true,
      "indexed": true
    },
    {
      "field": "first_name",
      "type": "string",
      "not-null": true,
      "indexed": false
    },
    {
      "field": "last_name",
      "type": "string",
      "not-null": true,
      "indexed": true
    },
    {
      "field": "gender",
      "type": "string",
      "not-null": true,
      "indexed": true
    },
    {
      "field": "age",
      "type": "number",
      "not-null": false,
      "indexed": false
    }
  ]
}

#####

GET {{BaseURL}}/v1/buckets/{{BucketName}}

####

DELETE {{BaseURL}}/v1/buckets/{{BucketName}}

####

@Key = id5

GET {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}

####

PUT {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}
Content-Type: application/json

{
  "id": "{{Key}}",
  "first_name": "Ana",
  "last_name": "Fialho",
  "gender": "F"
}

####

DELETE {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}

####

GET {{BaseURL}}/v1/buckets/{{BucketName}}/keys?gender=F
