@BaseURL = http://localhost:9090

####

GET {{BaseURL}}/v1/buckets

#####

@BucketName = people

POST {{BaseURL}}/v1/buckets
Content-Type: application/json

{
  "name": "{{BucketName}}",
  "schema": [
    {
      "field": "string",
      "type": "String",
      "not-null": true
    },
    {
      "field": "int",
      "type": "Int"
    },
    {
      "field": "float",
      "type": "Float",
      "not-null": true
    },
    {
      "field": "bool",
      "type": "Bool",
      "not-null": false
    }
  ]
}

#####

GET {{BaseURL}}/v1/buckets/{{BucketName}}

####

DELETE {{BaseURL}}/v1/buckets/{{BucketName}}

####

@Key = key

GET {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}

####

PUT {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}
Content-Type: application/json

{
  "string": "some text",
  "int": 123,
  "float": 123.456,
  "bool": false
}

####

DELETE {{BaseURL}}/v1/buckets/{{BucketName}}/keys/{{Key}}

####